//------------------------------------------------------------------------------
// <auto-generated>
//     ???? ??? ?????? ??????????.
//     ??????????? ??????:4.0.30319.42000
//
//     ????????? ? ???? ????? ????? ???????? ? ???????????? ?????? ? ????? ???????? ? ??????
//     ????????? ????????? ????.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace HuesSharp.Shaders {
	
	public class HuesXBlur26Effect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(HuesXBlur26Effect), 0);
		public static readonly DependencyProperty BlurAmountProperty = DependencyProperty.Register("BlurAmount", typeof(double), typeof(HuesXBlur26Effect), new UIPropertyMetadata(((double)(0D)), PixelShaderConstantCallback(0)));
		public HuesXBlur26Effect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("effects/HuesXBlur26Effect.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(BlurAmountProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		/// <summary>The scale of the blur (as a fraction of the input size).</summary>
		public double BlurAmount {
			get {
				return ((double)(this.GetValue(BlurAmountProperty)));
			}
			set {
				this.SetValue(BlurAmountProperty, value);
			}
		}
	}
}
