//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace HuesSharp.Shaders {
	
	public class SliceOmniV1Effect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(SliceOmniV1Effect), 0);
		public static readonly DependencyProperty SlideProperty = DependencyProperty.Register("BlurAmount", typeof(double), typeof(SliceOmniV1Effect), new UIPropertyMetadata(((double)(0D)), PixelShaderConstantCallback(0)));
		public SliceOmniV1Effect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("/effects/SliceOmniV1Effect.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(SlideProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		/// <summary>The scale of the slide (as a fraction of the input size).</summary>
		public double Slide {
			get {
				return ((double)(this.GetValue(SlideProperty)));
			}
			set {
				this.SetValue(SlideProperty, value);
			}
		}
	}
}
