using System.Windows.Media;

namespace MOPS
{
    public class Hues
    {

        public struct Palette
        {
            public string name;
            public Brush brush;

            public Palette(string f1, Brush f2)
            {
                name = f1; brush = f2;
            }
        }

        public static Palette[] hues_normal =
        {
            new Palette("Black", (SolidColorBrush)new BrushConverter().ConvertFromString("#000000")),
            new Palette("Brick", (SolidColorBrush)new BrushConverter().ConvertFromString("#550000")),
            new Palette("Crimson", (SolidColorBrush)new BrushConverter().ConvertFromString("#aa0000")),
            new Palette("Red", (SolidColorBrush)new BrushConverter().ConvertFromString("#ff0000")),
            new Palette("Turtle", (SolidColorBrush)new BrushConverter().ConvertFromString("#005500")),
            new Palette("Sludge", (SolidColorBrush)new BrushConverter().ConvertFromString("#555500")),
            new Palette("Brown", (SolidColorBrush)new BrushConverter().ConvertFromString("#aa5500")),
            new Palette("Orange", (SolidColorBrush)new BrushConverter().ConvertFromString("#ff5500")),
            new Palette("Green", (SolidColorBrush)new BrushConverter().ConvertFromString("#00aa00")),
            new Palette("Grass", (SolidColorBrush)new BrushConverter().ConvertFromString("#55aa00")),
            new Palette("Maize", (SolidColorBrush)new BrushConverter().ConvertFromString("#aaaa00")),
            new Palette("Citrus", (SolidColorBrush)new BrushConverter().ConvertFromString("#ffaa00")),
            new Palette("Lime", (SolidColorBrush)new BrushConverter().ConvertFromString("#00ff00")),
            new Palette("Leaf", (SolidColorBrush)new BrushConverter().ConvertFromString("#55ff00")),
            new Palette("Chartreuse", (SolidColorBrush)new BrushConverter().ConvertFromString("#aaff00")),
            new Palette("Yellow", (SolidColorBrush)new BrushConverter().ConvertFromString("#ffff00")),
            new Palette("Midnight", (SolidColorBrush)new BrushConverter().ConvertFromString("#000055")),
            new Palette("Plum", (SolidColorBrush)new BrushConverter().ConvertFromString("#550055")),
            new Palette("Pomegranate", (SolidColorBrush)new BrushConverter().ConvertFromString("#aa0055")),
            new Palette("Rose", (SolidColorBrush)new BrushConverter().ConvertFromString("#ff0055")),
            new Palette("Swamp", (SolidColorBrush)new BrushConverter().ConvertFromString("#005555")),
            new Palette("Dust", (SolidColorBrush)new BrushConverter().ConvertFromString("#555555")),
            new Palette("Dirt", (SolidColorBrush)new BrushConverter().ConvertFromString("#aa5555")),
            new Palette("Blossom", (SolidColorBrush)new BrushConverter().ConvertFromString("#ff5555")),
            new Palette("Sea", (SolidColorBrush)new BrushConverter().ConvertFromString("#00aa55")),
            new Palette("Ill", (SolidColorBrush)new BrushConverter().ConvertFromString("#55aa55")),
            new Palette("Haze", (SolidColorBrush)new BrushConverter().ConvertFromString("#aaaa55")),
            new Palette("Peach", (SolidColorBrush)new BrushConverter().ConvertFromString("#ffaa55")),
            new Palette("Spring", (SolidColorBrush)new BrushConverter().ConvertFromString("#00ff55")),
            new Palette("Mantis", (SolidColorBrush)new BrushConverter().ConvertFromString("#55ff55")),
            new Palette("Brilliant", (SolidColorBrush)new BrushConverter().ConvertFromString("#aaff55")),
            new Palette("Canary", (SolidColorBrush)new BrushConverter().ConvertFromString("#ffff55")),
            new Palette("Navy", (SolidColorBrush)new BrushConverter().ConvertFromString("#0000aa")),
            new Palette("Grape", (SolidColorBrush)new BrushConverter().ConvertFromString("#5500aa")),
            new Palette("Mauve", (SolidColorBrush)new BrushConverter().ConvertFromString("#aa00aa")),
            new Palette("Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#ff00aa")),
            new Palette("Cornflower", (SolidColorBrush)new BrushConverter().ConvertFromString("#0055aa")),
            new Palette("Deep", (SolidColorBrush)new BrushConverter().ConvertFromString("#5555aa")),
            new Palette("Lilac", (SolidColorBrush)new BrushConverter().ConvertFromString("#aa55aa")),
            new Palette("Lavender", (SolidColorBrush)new BrushConverter().ConvertFromString("#ff55aa")),
            new Palette("Aqua", (SolidColorBrush)new BrushConverter().ConvertFromString("#00aaaa")),
            new Palette("Steel", (SolidColorBrush)new BrushConverter().ConvertFromString("#55aaaa")),
            new Palette("Grey", (SolidColorBrush)new BrushConverter().ConvertFromString("#aaaaaa")),
            new Palette("Pink", (SolidColorBrush)new BrushConverter().ConvertFromString("#ffaaaa")),
            new Palette("Bay", (SolidColorBrush)new BrushConverter().ConvertFromString("#00ffaa")),
            new Palette("Marina", (SolidColorBrush)new BrushConverter().ConvertFromString("#55ffaa")),
            new Palette("Tornado", (SolidColorBrush)new BrushConverter().ConvertFromString("#aaffaa")),
            new Palette("Saltine", (SolidColorBrush)new BrushConverter().ConvertFromString("#ffffaa")),
            new Palette("Blue", (SolidColorBrush)new BrushConverter().ConvertFromString("#0000ff")),
            new Palette("Twilight", (SolidColorBrush)new BrushConverter().ConvertFromString("#5500ff")),
            new Palette("Orchid", (SolidColorBrush)new BrushConverter().ConvertFromString("#aa00ff")),
            new Palette("Magenta", (SolidColorBrush)new BrushConverter().ConvertFromString("#ff00ff")),
            new Palette("Azure", (SolidColorBrush)new BrushConverter().ConvertFromString("#0055ff")),
            new Palette("Liberty", (SolidColorBrush)new BrushConverter().ConvertFromString("#5555ff")),
            new Palette("Royalty", (SolidColorBrush)new BrushConverter().ConvertFromString("#aa55ff")),
            new Palette("Thistle", (SolidColorBrush)new BrushConverter().ConvertFromString("#ff55ff")),
            new Palette("Ocean", (SolidColorBrush)new BrushConverter().ConvertFromString("#00aaff")),
            new Palette("Sky", (SolidColorBrush)new BrushConverter().ConvertFromString("#55aaff")),
            new Palette("Periwinkle", (SolidColorBrush)new BrushConverter().ConvertFromString("#aaaaff")),
            new Palette("Carnation", (SolidColorBrush)new BrushConverter().ConvertFromString("#ffaaff")),
            new Palette("Cyan", (SolidColorBrush)new BrushConverter().ConvertFromString("#00ffff")),
            new Palette("Turquoise", (SolidColorBrush)new BrushConverter().ConvertFromString("#55ffff")),
            new Palette("Powder", (SolidColorBrush)new BrushConverter().ConvertFromString("#aaffff")),
            new Palette("White", (SolidColorBrush)new BrushConverter().ConvertFromString("#ffffff"))
        };          //  Macros would help with these.

        public static Palette[] hues_pastel =
        {
            new Palette("Mahogany", (SolidColorBrush)new BrushConverter().ConvertFromString("#CD4A4A")),
            new Palette("Banana Mania", (SolidColorBrush)new BrushConverter().ConvertFromString("#FAE7B5")),
            new Palette("Beaver", (SolidColorBrush)new BrushConverter().ConvertFromString("#9F8170")),
            new Palette("Black", (SolidColorBrush)new BrushConverter().ConvertFromString("#232323")),
            new Palette("Chestnut", (SolidColorBrush)new BrushConverter().ConvertFromString("#BC5D58")),
            new Palette("Copper", (SolidColorBrush)new BrushConverter().ConvertFromString("#DD9475")),
            new Palette("Cornflower", (SolidColorBrush)new BrushConverter().ConvertFromString("#9ACEEB")),
            new Palette("Denim", (SolidColorBrush)new BrushConverter().ConvertFromString("#2B6CC4")),
            new Palette("Desert Sand", (SolidColorBrush)new BrushConverter().ConvertFromString("#EFCDB8")),
            new Palette("Eggplant", (SolidColorBrush)new BrushConverter().ConvertFromString("#6E5160")),
            new Palette("Electric Lime", (SolidColorBrush)new BrushConverter().ConvertFromString("#1DF914")),
            new Palette("Fern", (SolidColorBrush)new BrushConverter().ConvertFromString("#71BC78")),
            new Palette("Goldenrod", (SolidColorBrush)new BrushConverter().ConvertFromString("#FCD975")),
            new Palette("Granny Smith Apple", (SolidColorBrush)new BrushConverter().ConvertFromString("#A8E4A0")),
            new Palette("Gray", (SolidColorBrush)new BrushConverter().ConvertFromString("#95918C")),
            new Palette("Green", (SolidColorBrush)new BrushConverter().ConvertFromString("#1CAC78")),
            new Palette("Hot Magenta", (SolidColorBrush)new BrushConverter().ConvertFromString("#FF1DCE")),
            new Palette("Inch Worm", (SolidColorBrush)new BrushConverter().ConvertFromString("#B2EC5D")),
            new Palette("Indigo", (SolidColorBrush)new BrushConverter().ConvertFromString("#5D76CB")),
            new Palette("Laser Lemon", (SolidColorBrush)new BrushConverter().ConvertFromString("#FDFC74")),
            new Palette("Lavender", (SolidColorBrush)new BrushConverter().ConvertFromString("#FCB4D5")),
            new Palette("Macaroni and Cheese", (SolidColorBrush)new BrushConverter().ConvertFromString("#FFBD88")),
            new Palette("Manatee", (SolidColorBrush)new BrushConverter().ConvertFromString("#979AAA")),
            new Palette("Mango Tango", (SolidColorBrush)new BrushConverter().ConvertFromString("#FF8243")),
            new Palette("Melon", (SolidColorBrush)new BrushConverter().ConvertFromString("#FDBCB4")),
            new Palette("Midnight Blue", (SolidColorBrush)new BrushConverter().ConvertFromString("#1A4876")),
            new Palette("Neon Carrot", (SolidColorBrush)new BrushConverter().ConvertFromString("#FFA343")),
            new Palette("Olive Green", (SolidColorBrush)new BrushConverter().ConvertFromString("#BAB86C")),
            new Palette("Orange", (SolidColorBrush)new BrushConverter().ConvertFromString("#FF7538")),
            new Palette("Orchid", (SolidColorBrush)new BrushConverter().ConvertFromString("#E6A8D7")),
            new Palette("Outer Space", (SolidColorBrush)new BrushConverter().ConvertFromString("#414A4C")),
            new Palette("Outrageous Orange", (SolidColorBrush)new BrushConverter().ConvertFromString("#FF6E4A")),
            new Palette("Pacific Blue", (SolidColorBrush)new BrushConverter().ConvertFromString("#1CA9C9")),
            new Palette("Periwinkle", (SolidColorBrush)new BrushConverter().ConvertFromString("#C5D0E6")),
            new Palette("Plum", (SolidColorBrush)new BrushConverter().ConvertFromString("#8E4585")),
            new Palette("Purple Heart", (SolidColorBrush)new BrushConverter().ConvertFromString("#7442C8")),
            new Palette("Raw Sienna", (SolidColorBrush)new BrushConverter().ConvertFromString("#D68A59")),
            new Palette("Razzmatazz", (SolidColorBrush)new BrushConverter().ConvertFromString("#E3256B")),
            new Palette("Red", (SolidColorBrush)new BrushConverter().ConvertFromString("#EE204D")),
            new Palette("Robin Egg Blue", (SolidColorBrush)new BrushConverter().ConvertFromString("#1FCECB")),
            new Palette("Royal Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#7851A9")),
            new Palette("Salmon", (SolidColorBrush)new BrushConverter().ConvertFromString("#FF9BAA")),
            new Palette("Scarlet", (SolidColorBrush)new BrushConverter().ConvertFromString("#FC2847")),
            new Palette("Sea Green", (SolidColorBrush)new BrushConverter().ConvertFromString("#9FE2BF")),
            new Palette("Sepia", (SolidColorBrush)new BrushConverter().ConvertFromString("#A5694F")),
            new Palette("Shadow", (SolidColorBrush)new BrushConverter().ConvertFromString("#8A795D")),
            new Palette("Shamrock", (SolidColorBrush)new BrushConverter().ConvertFromString("#45CEA2")),
            new Palette("Shocking Pink", (SolidColorBrush)new BrushConverter().ConvertFromString("#FB7EFD")),
            new Palette("Spring Green", (SolidColorBrush)new BrushConverter().ConvertFromString("#ECEABE")),
            new Palette("Sunset Orange", (SolidColorBrush)new BrushConverter().ConvertFromString("#FD5E53")),
            new Palette("Tan", (SolidColorBrush)new BrushConverter().ConvertFromString("#FAA76C")),
            new Palette("Tickle Me Pink", (SolidColorBrush)new BrushConverter().ConvertFromString("#FC89AC")),
            new Palette("Timberwolf", (SolidColorBrush)new BrushConverter().ConvertFromString("#DBD7D2")),
            new Palette("Tropical Rain Forest", (SolidColorBrush)new BrushConverter().ConvertFromString("#17806D")),
            new Palette("Turquoise Blue", (SolidColorBrush)new BrushConverter().ConvertFromString("#77DDE7")),
            new Palette("Vivid Tangerine", (SolidColorBrush)new BrushConverter().ConvertFromString("#FFA089")),
            new Palette("Vivid Violet", (SolidColorBrush)new BrushConverter().ConvertFromString("#8F509D")),
            new Palette("White", (SolidColorBrush)new BrushConverter().ConvertFromString("#EDEDED")),
            new Palette("Wild Strawberry", (SolidColorBrush)new BrushConverter().ConvertFromString("#FF43A4")),
            new Palette("Wild Watermelon", (SolidColorBrush)new BrushConverter().ConvertFromString("#FC6C85")),
            new Palette("Wisteria", (SolidColorBrush)new BrushConverter().ConvertFromString("#CDA4DE")),
            new Palette("Yellow", (SolidColorBrush)new BrushConverter().ConvertFromString("#FCE883")),
            new Palette("Yellow Green", (SolidColorBrush)new BrushConverter().ConvertFromString("#C5E384")),
            new Palette("Yellow Orange", (SolidColorBrush)new BrushConverter().ConvertFromString("#FFB653")),
        };

        public static Palette[] hues_weed =
        {
            new Palette("Green", (SolidColorBrush)new BrushConverter().ConvertFromString("#00FF00")),
            new Palette("Lizard", (SolidColorBrush)new BrushConverter().ConvertFromString("#5A6351")),
            new Palette("Cactus", (SolidColorBrush)new BrushConverter().ConvertFromString("#636F57")),
            new Palette("Kakapo", (SolidColorBrush)new BrushConverter().ConvertFromString("#4A7023")),
            new Palette("Wet Moss", (SolidColorBrush)new BrushConverter().ConvertFromString("#3D5229")),
            new Palette("Tree Moss", (SolidColorBrush)new BrushConverter().ConvertFromString("#659D32")),
            new Palette("Lime Rind", (SolidColorBrush)new BrushConverter().ConvertFromString("#324F17")),
            new Palette("Flight Jacket", (SolidColorBrush)new BrushConverter().ConvertFromString("#7F8778")),
            new Palette("Green Mist", (SolidColorBrush)new BrushConverter().ConvertFromString("#BCED91")),
            new Palette("Holly", (SolidColorBrush)new BrushConverter().ConvertFromString("#488214")),
            new Palette("Mtn Dew Bottle", (SolidColorBrush)new BrushConverter().ConvertFromString("#577A3A")),
            new Palette("Seaweed Roll", (SolidColorBrush)new BrushConverter().ConvertFromString("#748269")),
            new Palette("Neon Green", (SolidColorBrush)new BrushConverter().ConvertFromString("#83F52C")),
            new Palette("Lichen", (SolidColorBrush)new BrushConverter().ConvertFromString("#C0D9AF")),
            new Palette("Guacamole", (SolidColorBrush)new BrushConverter().ConvertFromString("#A6D785")),
            new Palette("Pond Scum", (SolidColorBrush)new BrushConverter().ConvertFromString("#687E5A")),
            new Palette("Douglas Fir", (SolidColorBrush)new BrushConverter().ConvertFromString("#3F602B")),
            new Palette("Royal Palm", (SolidColorBrush)new BrushConverter().ConvertFromString("#3F6826")),
            new Palette("Seaweed", (SolidColorBrush)new BrushConverter().ConvertFromString("#646F5E")),
            new Palette("Noble Fir", (SolidColorBrush)new BrushConverter().ConvertFromString("#476A34")),
            new Palette("Green Led", (SolidColorBrush)new BrushConverter().ConvertFromString("#5DFC0A")),
            new Palette("Spinach", (SolidColorBrush)new BrushConverter().ConvertFromString("#435D36")),
            new Palette("Frog", (SolidColorBrush)new BrushConverter().ConvertFromString("#84BE6A")),
            new Palette("Emerald", (SolidColorBrush)new BrushConverter().ConvertFromString("#5B9C64")),
            new Palette("Circuit Board", (SolidColorBrush)new BrushConverter().ConvertFromString("#3A6629")),
            new Palette("Sapgreen", (SolidColorBrush)new BrushConverter().ConvertFromString("#308014")),
            new Palette("Pool Table", (SolidColorBrush)new BrushConverter().ConvertFromString("#31B94D")),
            new Palette("Leaf", (SolidColorBrush)new BrushConverter().ConvertFromString("#55AE3A")),
            new Palette("Grass", (SolidColorBrush)new BrushConverter().ConvertFromString("#4DBD33")),
            new Palette("Snake", (SolidColorBrush)new BrushConverter().ConvertFromString("#596C56")),
            new Palette("100 Euro", (SolidColorBrush)new BrushConverter().ConvertFromString("#86C67C")),
            new Palette("Night Vision", (SolidColorBrush)new BrushConverter().ConvertFromString("#7BCC70")),
            new Palette("Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#A020F0")),
            new Palette("Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#9B30FF")),
            new Palette("Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#912CEE")),
            new Palette("Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#7D26CD")),
            new Palette("Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#AA00FF")),
            new Palette("Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#800080")),
            new Palette("Turnip", (SolidColorBrush)new BrushConverter().ConvertFromString("#A74CAB")),
            new Palette("Violet", (SolidColorBrush)new BrushConverter().ConvertFromString("#8F5E99")),
            new Palette("Eggplant", (SolidColorBrush)new BrushConverter().ConvertFromString("#816687")),
            new Palette("Grape", (SolidColorBrush)new BrushConverter().ConvertFromString("#CC00FF")),
            new Palette("Wild Violet", (SolidColorBrush)new BrushConverter().ConvertFromString("#820BBB")),
            new Palette("Concord Grape", (SolidColorBrush)new BrushConverter().ConvertFromString("#660198")),
            new Palette("Garden Plum", (SolidColorBrush)new BrushConverter().ConvertFromString("#71637D")),
            new Palette("Purple Fish", (SolidColorBrush)new BrushConverter().ConvertFromString("#B272A6")),
            new Palette("Ultramarine Violet", (SolidColorBrush)new BrushConverter().ConvertFromString("#5C246E")),
            new Palette("Purple Rose", (SolidColorBrush)new BrushConverter().ConvertFromString("#5E2D79")),
            new Palette("Sea Urchin", (SolidColorBrush)new BrushConverter().ConvertFromString("#683A5E")),
            new Palette("Cobalt Violet Deep", (SolidColorBrush)new BrushConverter().ConvertFromString("#91219E")),
            new Palette("Plum", (SolidColorBrush)new BrushConverter().ConvertFromString("#8B668B")),
            new Palette("Dark Orchid", (SolidColorBrush)new BrushConverter().ConvertFromString("#9932CD")),
            new Palette("Violet Flower", (SolidColorBrush)new BrushConverter().ConvertFromString("#BF5FFF")),
            new Palette("Purple Candy", (SolidColorBrush)new BrushConverter().ConvertFromString("#BDA0CB")),
            new Palette("Deep Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#551A8B")),
            new Palette("Thistle", (SolidColorBrush)new BrushConverter().ConvertFromString("#B5509C")),
            new Palette("Dark Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#871F78")),
            new Palette("Purple Ink", (SolidColorBrush)new BrushConverter().ConvertFromString("#9C6B98")),
            new Palette("Orchid", (SolidColorBrush)new BrushConverter().ConvertFromString("#DB70DB")),
            new Palette("True Purple", (SolidColorBrush)new BrushConverter().ConvertFromString("#990099")),
            new Palette("Darkmagenta", (SolidColorBrush)new BrushConverter().ConvertFromString("#8B008B")),
            new Palette("Harold's Crayon", (SolidColorBrush)new BrushConverter().ConvertFromString("#B62084")),
            new Palette("Purple Rain", (SolidColorBrush)new BrushConverter().ConvertFromString("#694489")),
            new Palette("Gold", (SolidColorBrush)new BrushConverter().ConvertFromString("#FFD700"))
        };
    }
}